### ISSUE TITLE
Questions/Concerns

### ISSUE THREAD

**Issue by crabbynick4** [nishi7409/ClanLabs-OpenSourced#5]
Does it auto promote users?

Does it have a way to roll back abuse?

Can it message users by chance?

Does it have an in-game API like Clan Labs?

I am really looking forward to using this especially since its free but kindly ask for these features or confirmation of said features to make it more worth my while.

**Comment by nishi7409** [comment]
Yes, it auto promotes users. 

It doesn't roll back abuse, it's practically impossible to abuse with a system like this though.

It can message users; however, I've removed that snippet because let's be honest--ROBLOX doesn't like this stuff (automation done by third-party services).  Plus, it'd trigger an _are you a human_ check.

You can work with the database URL in the game.  I have no knowledge of Lua so I didn't venture down that path.  When I was _working_ with Marcuses, we got the help from a Lua scripter by the name of Avallex.  I don't remember much else, it's been some time since I've touched the game.

I'm not adding any more features to the source code.  I encourage you to learn how to code yourself and make changes if needed.  This repository is __as is__, meaning there will no longer be any changes.

**Comment by crabbynick4** [comment]
If it breaks will you update it? Like if it fully breaks just not feature upgrades?

**Comment by nishi7409** [comment]
I will not be updating anything.  I'm more than welcome to work on something brand new, for a charge of course.  Contact me on Discord @ nishi#1028 (if that's the case).
